require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Slashy' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Firebase Notifications
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging', '~> 6.22.0'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  target 'SlashyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  use_native_modules!
end

target 'Slashy-tvOS' do
  # Pods for Slashy-tvOS

  target 'Slashy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
